// The trip itself — the leg list both audience pages share (Tampa → Buga).
// partner.js appends the Guayaquil reunion; friends-family.js stops at Buga.
//
// Prose (title where it's a phrase, subtitle, body) is authored as { en, es }
// and resolved per locale in toRenderModel.

/** @type {import('@trip/shared/lib/normalizeConfig.js').Entry[]} */
export const legs = [
  {
    id: "tampa-1",
    dateStart: "2026-08-29",
    dateEnd: "2026-09-03",
    title: "Tampa",
    subtitle: { en: "United States", es: "Estados Unidos" },
    icon: "🌴",
    kind: "stay",
    coords: [27.95, -82.46],
    body: {
      en: "Where it starts. Warm nights, half-packed bags, last-minute everything.",
      es: "Donde empieza todo. Noches cálidas, maletas a medio hacer, todo a última hora.",
    },
  },
  {
    id: "atlantic",
    dateStart: "2026-09-04",
    title: { en: "Over the Atlantic", es: "Sobre el Atlántico" },
    subtitle: "TPA → ARN",
    icon: "✈️",
    kind: "travel",
    coords: [48, -32],
    body: { en: "An ocean in one sitting.", es: "Un océano de una sentada." },
  },
  {
    id: "stockholm",
    dateStart: "2026-09-04",
    dateEnd: "2026-09-09",
    title: { en: "Stockholm", es: "Estocolmo" },
    subtitle: { en: "Sweden", es: "Suecia" },
    icon: "🛶",
    kind: "stay",
    coords: [59.33, 18.07],
    body: {
      en: "Islands, cold clean water, cinnamon buns as the light goes at 3pm.",
      es: "Islas, agua fría y limpia, bollos de canela mientras la luz se va a las 3 de la tarde.",
    },
  },
  {
    id: "zurich",
    dateStart: "2026-09-09",
    title: { en: "Zürich", es: "Zúrich" },
    subtitle: { en: "Switzerland", es: "Suiza" },
    icon: "🚋",
    kind: "stay",
    coords: [47.37, 8.54],
    body: {
      en: "Land, find the platform, take the train south into the mountains.",
      es: "Aterrizar, buscar el andén, tomar el tren al sur hacia las montañas.",
    },
  },
  {
    id: "interlaken",
    dateStart: "2026-09-10",
    dateEnd: "2026-09-12",
    title: "Interlaken",
    subtitle: { en: "Switzerland", es: "Suiza" },
    icon: "🏔️",
    kind: "stay",
    coords: [46.69, 7.86],
    body: {
      en: "Two lakes, one valley, and a lot of time spent looking up.",
      es: "Dos lagos, un valle, y mucho rato mirando hacia arriba.",
    },
  },
  {
    id: "lucerne",
    dateStart: "2026-09-12",
    title: { en: "Lucerne", es: "Lucerna" },
    subtitle: { en: "Switzerland", es: "Suiza" },
    icon: "🌉",
    kind: "travel",
    coords: [47.05, 8.31],
    body: {
      en: "Day trip: wooden bridge, painted rafters, slow green water.",
      es: "Excursión: puente de madera, vigas pintadas, agua verde y lenta.",
    },
  },
  {
    id: "zurich-2",
    dateStart: "2026-09-12",
    dateEnd: "2026-09-13",
    title: { en: "Zürich", es: "Zúrich" },
    subtitle: { en: "Switzerland", es: "Suiza" },
    icon: "🌃",
    kind: "stay",
    coords: [47.37, 8.54],
    body: {
      en: "Back in the city for a night before the flight south.",
      es: "De vuelta en la ciudad por una noche antes del vuelo al sur.",
    },
  },
  {
    id: "barcelona",
    dateStart: "2026-09-13",
    dateEnd: "2026-09-17",
    title: "Barcelona",
    subtitle: { en: "Spain", es: "España" },
    icon: "🥘",
    kind: "stay",
    coords: [41.39, 2.16],
    body: {
      en: "Back to the sea, and a language I think in without trying.",
      es: "De vuelta al mar, y a un idioma en el que pienso sin proponérmelo.",
    },
  },
  {
    id: "menorca",
    dateStart: "2026-09-18",
    dateEnd: "2026-09-22",
    title: "Menorca",
    subtitle: { en: "Spain", es: "España" },
    icon: "🐚",
    kind: "stay",
    coords: [39.89, 4.26],
    body: {
      en: "Coves the colour of a swimming pool. Nothing to do, on purpose.",
      es: "Calas del color de una piscina. Nada que hacer, a propósito.",
    },
  },
  {
    id: "madrid",
    dateStart: "2026-09-22",
    dateEnd: "2026-09-26",
    title: "Madrid",
    subtitle: { en: "Spain", es: "España" },
    icon: "🎨",
    kind: "stay",
    coords: [40.42, -3.7],
    body: {
      en: "City heat, dinner at eleven, one more room full of paintings.",
      es: "Calor de ciudad, cena a las once, una sala más llena de cuadros.",
    },
  },
  {
    id: "tampa-2",
    dateStart: "2026-09-26",
    dateEnd: "2026-10-03",
    title: "Tampa",
    subtitle: { en: "United States", es: "Estados Unidos" },
    icon: "🌴",
    kind: "stay",
    coords: [27.95, -82.46],
    body: {
      en: "Same porch, same heat. Halfway home now.",
      es: "El mismo porche, el mismo calor. Ya a mitad de camino a casa.",
    },
  },
  {
    id: "cali-hop",
    dateStart: "2026-10-03",
    dateEnd: "2026-10-04",
    title: { en: "Overnight to Cali", es: "De noche hacia Cali" },
    subtitle: "TPA → CLO",
    icon: "🌙",
    kind: "travel",
    coords: [12, -78],
    body: {
      en: "A red-eye, then sunrise over the Cauca valley.",
      es: "Un vuelo de madrugada, y luego el amanecer sobre el valle del Cauca.",
    },
  },
  {
    id: "buga",
    dateStart: "2026-10-04",
    dateEnd: "2026-10-31",
    title: "Buga",
    subtitle: "Colombia",
    icon: "⛪",
    kind: "stay",
    coords: [3.9, -76.3],
    body: {
      en: "Home ground. This is where the counting gets serious.",
      es: "Terreno conocido. Aquí es donde la cuenta se pone seria.",
    },
  },
];
