// The original page, expressed as a PageConfig (see @trip/shared normalizeConfig).
// This is the seed / reference page and must keep rendering exactly as the
// hand-authored version did. Served at "/".

/** @type {import('@trip/shared/lib/normalizeConfig.js').PageConfig} */
export default {
  meta: {
    slug: "juanjo",
    locale: "en",
    occasion: "romantic",
    status: "published",
    plan: "paid",
  },
  theme: {
    preset: "sunset",
    accent: "#FF9E9E",
    fontPair: "bricolage-nunito",
    heroStyle: "boardingPass",
    motion: true,
  },
  people: {
    away: [{ name: "Juanjo" }],
    home: [{ name: "Nicolle" }],
    whoIsAway: "away",
    relationship: "partner",
  },
  hero: {
    title: "The long way\nback to Nicolle",
    subtitle:
      "Where he is right now, and exactly how long until he walks through the arrivals gate in Guayaquil.",
  },
  target: {
    at: "2026-10-31T20:00:00-05:00",
    tz: "America/Guayaquil",
    placeName: "Guayaquil",
    label: "the arrivals gate in Guayaquil",
    dateLabel: "31 October 2026",
    coords: [-2.19, -79.89],
    onZero: {
      title: "home",
      body: "the trip was pointed here the whole time",
      confetti: true,
    },
  },
  entries: [
    {
      id: "tampa-1",
      dateStart: "2026-08-29",
      dateEnd: "2026-09-03",
      title: "Tampa",
      subtitle: "United States",
      icon: "🌴",
      kind: "stay",
      coords: [27.95, -82.46],
      body: "Where it starts. Warm nights, half-packed bags, last-minute everything.",
    },
    {
      id: "atlantic",
      dateStart: "2026-09-04",
      title: "Over the Atlantic",
      subtitle: "TPA → ARN",
      icon: "✈️",
      kind: "travel",
      coords: [48, -32],
      body: "An ocean in one sitting.",
    },
    {
      id: "stockholm",
      dateStart: "2026-09-04",
      dateEnd: "2026-09-09",
      title: "Stockholm",
      subtitle: "Sweden",
      icon: "🛶",
      kind: "stay",
      coords: [59.33, 18.07],
      body: "Islands, cold clean water, cinnamon buns as the light goes at 3pm.",
    },
    {
      id: "zurich",
      dateStart: "2026-09-09",
      title: "Zürich",
      subtitle: "Switzerland",
      icon: "🚋",
      kind: "stay",
      coords: [47.37, 8.54],
      body: "Land, find the platform, take the train south into the mountains.",
    },
    {
      id: "interlaken",
      dateStart: "2026-09-10",
      dateEnd: "2026-09-11",
      title: "Interlaken",
      subtitle: "Switzerland",
      icon: "🏔️",
      kind: "stay",
      coords: [46.69, 7.86],
      body: "Two lakes, one valley, and a lot of time spent looking up.",
    },
    {
      id: "lucerne",
      dateStart: "2026-09-12",
      title: "Lucerne",
      subtitle: "Switzerland",
      icon: "🌉",
      kind: "stay",
      coords: [47.05, 8.31],
      body: "Wooden bridge, painted rafters, slow green water.",
    },
    {
      id: "barcelona",
      dateStart: "2026-09-13",
      dateEnd: "2026-09-17",
      title: "Barcelona",
      subtitle: "Spain",
      icon: "🥘",
      kind: "stay",
      coords: [41.39, 2.16],
      body: "Back to the sea, and a language I think in without trying.",
    },
    {
      id: "menorca",
      dateStart: "2026-09-18",
      dateEnd: "2026-09-22",
      title: "Menorca",
      subtitle: "Spain",
      icon: "🐚",
      kind: "stay",
      coords: [39.89, 4.26],
      body: "Coves the colour of a swimming pool. Nothing to do, on purpose.",
    },
    {
      id: "madrid",
      dateStart: "2026-09-22",
      dateEnd: "2026-09-26",
      title: "Madrid",
      subtitle: "Spain",
      icon: "🎨",
      kind: "stay",
      coords: [40.42, -3.7],
      body: "City heat, dinner at eleven, one more room full of paintings.",
    },
    {
      id: "tampa-2",
      dateStart: "2026-09-26",
      dateEnd: "2026-10-03",
      title: "Tampa",
      subtitle: "United States",
      icon: "🌴",
      kind: "stay",
      coords: [27.95, -82.46],
      body: "Same porch, same heat. Halfway home now.",
    },
    {
      id: "cali-hop",
      dateStart: "2026-10-03",
      dateEnd: "2026-10-04",
      title: "Overnight to Cali",
      subtitle: "TPA → CLO",
      icon: "🌙",
      kind: "travel",
      coords: [12, -78],
      body: "A red-eye, then sunrise over the Cauca valley.",
    },
    {
      id: "buga",
      dateStart: "2026-10-04",
      dateEnd: "2026-10-31",
      title: "Buga",
      subtitle: "Colombia",
      icon: "⛪",
      kind: "stay",
      coords: [3.9, -76.3],
      body: "Home ground. This is where the counting gets serious.",
    },
    {
      id: "guayaquil",
      dateStart: "2026-10-31",
      title: "Guayaquil",
      subtitle: "Ecuador",
      icon: "💛",
      kind: "reunion",
      coords: [-2.19, -79.89],
      body: "Nicolle, at the gate. The whole trip was pointed here.",
    },
  ],
  note: {
    body: "Ya alistándome para Halloween en Guayaquil 💛",
  },
  stats: {
    show: ["distance", "stopsLeft", "percent"],
  },
  share: { ogAuto: true },
  branding: { showFooter: true },
};
